@echo off
chcp 65001 >nul 2>&1
setlocal EnableDelayedExpansion
title AMS JobAssist - Deinstallation

:: ============================================================================
::  AMS JobAssist - Uninstaller
::  Auto-generated by install.bat — paths are derived from this file's location.
:: ============================================================================

:: The install directory is wherever this script lives
set "INSTALL_DIR=%~dp0"
:: Remove trailing backslash for clean display
if "!INSTALL_DIR:~-1!"=="\" set "INSTALL_DIR=!INSTALL_DIR:~0,-1!"

set "DATA_DIR=%APPDATA%\AMS-JobAssist"
set "STARTMENU=%APPDATA%\Microsoft\Windows\Start Menu\Programs\AMS JobAssist"

cls
echo.
echo  ================================================================
echo     AMS JobAssist - Deinstallation
echo  ================================================================
echo.
echo     Folgendes wird entfernt:
echo.
echo       - Programmdateien aus:
echo         !INSTALL_DIR!
echo.
echo       - Startmenue-Eintraege
echo       - Desktop-Verknuepfung (falls vorhanden)
echo       - Eintrag in "Programme und Features"
echo.
echo     Ihre Daten in:
echo       !DATA_DIR!
echo     bleiben erhalten (es sei denn, Sie waehlen Option 2).
echo.
echo  ----------------------------------------------------------------
echo.
choice /c 12A /n /m "     [1] Programm entfernen  [2] Programm + Daten entfernen  [A] Abbrechen: "
echo.
if errorlevel 3 goto :DONE
if errorlevel 2 goto :FULL_REMOVE
goto :PROGRAM_ONLY

:FULL_REMOVE
echo.
echo     WARNUNG: Alle Daten werden DAUERHAFT geloescht!
echo     Lebenslaeufe, Protokolle und KI-Modelle werden entfernt.
echo.
choice /c JN /n /m "     Sind Sie sicher? [J] Ja  [N] Nein: "
echo.
if errorlevel 2 goto :DONE

echo     Loesche Daten...
if exist "!DATA_DIR!" rmdir /s /q "!DATA_DIR!"
echo     [OK] Daten geloescht.
echo.

:PROGRAM_ONLY
echo     Entferne Programm...
echo.

:: Remove Start Menu entries
if exist "!STARTMENU!" rmdir /s /q "!STARTMENU!"
echo     [OK] Startmenue-Eintraege entfernt.

:: Remove Desktop shortcut
del /q "%USERPROFILE%\Desktop\AMS JobAssist.lnk" 2>nul
echo     [OK] Desktop-Verknuepfung entfernt.

:: Remove registry entry (Add/Remove Programs)
reg delete "HKCU\Software\Microsoft\Windows\CurrentVersion\Uninstall\AMS JobAssist" /f 2>nul
echo     [OK] Registrierungseintrag entfernt.

:: Remove program files — schedule self-deletion since we can't delete ourselves
echo     [OK] Programmdateien werden nach Beenden dieses Fensters entfernt.
echo.
echo  ================================================================
echo     Deinstallation abgeschlossen!
echo  ================================================================
echo.
pause

:: Self-destruct: after this script exits, delete the install directory
:: The /b flag runs it without a visible window; timeout gives this script time to exit
start /b "" cmd /c "timeout /t 3 /nobreak >nul & rmdir /s /q "!INSTALL_DIR!""
exit /b 0

:DONE
echo     Abgebrochen. Nichts wurde geaendert.
echo.
pause
exit /b 0
